@startuml
start
skinparam titleBorderRoundCorner 14
skinparam titleBorderColor red
skinparam titleBackgroundColor Moccasin
title **Алгоритм выполнения контролей по данным консолидации**
:Получение отчета по параметрам:
*uuid задачи сбора отчетности
*код отчетности
*роль субъекта отчетности
*статус отчетности
*инн
*кпп
*бюджет;
note left
http-запросы, 
с указанными 
параметрами
end note
:Преобразование отчета в формат планирования;
note left
Используются 
xpath-выражения,
указанные в 
настройках контроля
end note
:Фильтрация данных отчета;
note left
Используется фильтр,
указанный в 
настройках контроля
end note
:Фильтрация данных планирования;
:Сравнение сумм данных планирования и консолидации;
:Вывод результата;
note left
html-таблица
со списком 
классификации
и сумм
end note
stop
@enduml