@startuml
start
skinparam titleBorderRoundCorner 14
skinparam titleBorderColor red
skinparam titleBackgroundColor Moccasin
title **Алгоритм синхронизации с НСИ**
:Формирование параметров синхронизации
* выбор справочников
* установка параметов для каждого справочника
**  метка времени
**  количество объектов в пакете;
repeat :Инициализация цикла по выбранным справочникам
:Выбор справочника;
repeat :Формирование soap-запроса получения данных из НСИ 
:Получение данных;
if (Есть данные?) then
  :Обработать данные;
note left
Для каждого 
справочника 
определен свой 
алгоритм обработки
end note
  :Сдвинуть метку времени; 
note left
Приходит из НСИ и
используется при 
запросе данных
end note
endif
  repeat while (Есть данные?)
repeat while (Есть еще справочники?)
stop
@enduml